pub(super) fn get(record: &str, signature: &str) -> Option<&'static str> {
    match (record, signature) {
        ("NPC_", "ACBS") => Some("Configuration"),
        ("NPC_", "AIDT") => Some("AI Data"),
        ("NPC_", "DNAM") => Some("Player Skills"),
        ("NPC_", "RNAM") => Some("Race"),
        ("NPC_", "CNAM") => Some("Class"),
        ("NPC_", "DOFT") => Some("Default Outfit"),
        ("NPC_", "SOFT") => Some("Sleeping Outfit"),
        ("NPC_", "DPLT") => Some("Default Package List"),
        ("NPC_", "CRIF") => Some("Crime Faction"),
        ("NPC_", "NAM6") => Some("Height"),
        ("NPC_", "NAM7") => Some("Weight"),
        ("NPC_", "FULL") => Some("Name"),
        ("NPC_", "SHRT") => Some("Short Name"),
        ("NPC_", "SNAM") => Some("Faction"),
        ("NPC_", "INAM") => Some("Death Item"),
        ("NPC_", "VTCK") => Some("Voice"),
        ("NPC_", "TPLT") => Some("Template"),
        ("NPC_", "SPLO") => Some("Actor Effect"),
        ("NPC_", "ATKR") => Some("Attack Race"),
        ("NPC_", "ATKD") => Some("Attack Data"),
        ("NPC_", "PKID") => Some("Package"),
        ("NPC_", "CNTO") => Some("Item"),
        ("NPC_", "HCLF") => Some("Hair Color"),
        ("NPC_", "ZNAM") => Some("Combat Style"),
        ("NPC_", "QNAM") => Some("Texture Lighting"),
        ("NPC_", "TINI") => Some("Tint Index"),
        ("NPC_", "TINC") => Some("Tint Color"),
        ("NPC_", "TINV") => Some("Interpolation Value"),
        ("NPC_", "TIAS") => Some("Tint Preset"),
        _ => None,
    }
}
