pub(super) fn get(record: &str, signature: &str) -> Option<&'static str> {
    match (record, signature) {
        ("QUST", "VMAD") => Some("Virtual Machine Adapter"),
        ("FACT", "DATA") => Some("Flags"),
        ("FACT", "CRVA") => Some("Crime Values"),
        ("FACT", "VENV") => Some("Vendor Values"),
        ("FACT", "PLVD") => Some("Location"),
        ("FACT", "FULL") => Some("Name"),
        ("FACT", "XNAM") => Some("Relation"),
        ("RACE", "DATA") => Some("Data"),
        ("RACE", "WNAM") => Some("Skin"),
        ("RACE", "VNAM") => Some("Equipment Flags"),
        ("RACE", "FULL") => Some("Name"),
        ("RACE", "DESC") => Some("Description"),
        ("RACE", "BOD2") => Some("Biped Body Template"),
        ("RACE", "ATKD") => Some("Attack Data"),
        ("RACE", "ATKE") => Some("Attack Event"),
        ("RACE", "MTNM") => Some("Movement Type Name"),
        ("RACE", "PHWT") => Some("Phoneme Target Weight"),
        ("RACE", "TINL") => Some("Total Number of Tints in List"),
        ("RACE", "TINT") => Some("Tint File Name"),
        ("RACE", "TINI") => Some("Tint Index"),
        ("RACE", "TINP") => Some("Mask Type"),
        ("RACE", "TIND") => Some("Preset Default"),
        ("RACE", "TINC") => Some("Tint Color"),
        ("RACE", "TINV") => Some("Tint Default Value"),
        ("RACE", "TIRS") => Some("Tint Preset Index"),
        _ => None,
    }
}
